# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e5b4a6e2fa451ecb72e5d63f48d24ea28ecda95c65ea1188612562ad826ee42fdb49185a6b19caf531154835d7fb7fbfbac64cd6f55512fe00a027c102d99e5

test:
  secret_key_base: 58599c64a46d0b2f519c901705ea2fd9f29031a0c72bbbd696d74791529c954ad8680a4a32340c27dc5e17687bdb03d4ea7ccf4fc79bfa12dc0fe0e4bf4c9ed3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
